'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import { readingFor, skyFor, skyStopsFor, cloudCoverFor, rgb } from '../lib/sky'
import Precipitation from './Precipitation'
import CloudShader from './CloudShader'

/**
 * The weather inside the city panel: sky, cloud, precipitation and lightning.
 *
 * The cloud is fractal noise generated by the browser from an SVG filter, not a
 * gradient and not a shipped image. Noise is what gives cloud its wispy, uneven
 * edge; stacked gradients always read as balloons. Three bands of it at different
 * scales and speeds make a sky with depth.
 */

type Props = {
  /** OpenWeather condition id of the city currently on screen. */
  code?: number
  isDay: boolean
  /** Fills the nearest positioned box rather than the window. */
  inset?: boolean
}

/**
 * An SVG turbulence tile as a data URI, used as a repeating background image.
 *
 * `stitchTiles` makes the noise continue across copies, so a strip of it can be
 * scrolled sideways for ever without a seam. The colour matrix throws away the
 * generated colour and keeps a soft alpha ramp, which is the cloud.
 */
function cloudTile(frequency: number, octaves: number, cut: number, gain: number): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300">` +
    `<filter id="c" x="0" y="0" width="100%" height="100%">` +
    `<feTurbulence type="fractalNoise" baseFrequency="${frequency}" numOctaves="${octaves}" stitchTiles="stitch" seed="7"/>` +
    `<feColorMatrix type="matrix" values="` +
    `0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  ${gain} 0 0 0 ${cut}"/>` +
    `</filter>` +
    `<rect width="600" height="300" filter="url(#c)"/>` +
    `</svg>`
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`
}

/**
 * A drawn cloud silhouette, as a mask.
 *
 * Noise on its own gives texture but no form, which is why an unmasked sheet of it
 * reads as smoke. Cutting that noise to a drawn outline gives the cloud a shape and
 * a base, and the two together are how painted cloud is built: the outline says
 * where the cloud is, the noise says what it is made of.
 *
 * Wide and repeating, so a strip of cloud is a run of masses rather than one shape.
 */
function cloudMask(): string {
  const lobe = (cx: number, cy: number, rx: number, ry: number) =>
    `<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="#fff"/>`

  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300" viewBox="0 0 600 300">` +
    `<g filter="url(#s)">` +
    // A soft floor the masses sit on, so the cloud has an underside and not a fringe.
    `<rect x="0" y="176" width="600" height="60" rx="30" fill="#fff"/>` +
    lobe(84, 168, 78, 54) + lobe(150, 140, 62, 62) + lobe(214, 164, 70, 48) +
    lobe(286, 128, 74, 70) + lobe(352, 156, 58, 52) + lobe(424, 138, 82, 64) +
    lobe(498, 166, 66, 50) + lobe(560, 146, 56, 58) +
    `</g>` +
    `<defs><filter id="s"><feGaussianBlur stdDeviation="16"/></filter></defs>` +
    `</svg>`
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`
}

const CLOUD_MASK = cloudMask()

type Band = { height: string; top: string; tile: string; size: string; seconds: number; opacity: number }

const BANDS: Band[] = [
  {
    height: '62%', top: '-8%',
    tile: cloudTile(0.009, 4, -0.34, 1.5), size: '620px 280px',
    seconds: 240, opacity: 0.5,
  },
  {
    height: '48%', top: '6%',
    tile: cloudTile(0.016, 5, -0.5, 2.1), size: '440px 200px',
    seconds: 150, opacity: 0.55,
  },
  {
    height: '38%', top: '-4%',
    tile: cloudTile(0.026, 5, -0.62, 2.6), size: '300px 140px',
    seconds: 95, opacity: 0.45,
  },
  // A low band, so the sky is weather all the way down rather than cloud on a wall.
  {
    height: '70%', top: '42%',
    tile: cloudTile(0.012, 4, -0.46, 1.7), size: '520px 240px',
    seconds: 300, opacity: 0.3,
  },
]

/**
 * The layer that passes over the reading. Coarser and faster than the bands behind,
 * because something close moves further across the view in the same time.
 */
const FRONT_WISP = {
  tile: cloudTile(0.008, 3, -0.58, 1.9),
  size: '840px 380px',
  seconds: 62,
  opacity: 0.22,
}

const STARS = [
  { left: 8, top: 12, size: 2, seconds: 4.5, delay: 0 },
  { left: 17, top: 30, size: 1, seconds: 5.5, delay: -1.5 },
  { left: 26, top: 8, size: 2, seconds: 3.2, delay: -0.7 },
  { left: 34, top: 22, size: 1, seconds: 6, delay: -2.2 },
  { left: 43, top: 37, size: 1, seconds: 4.8, delay: -3.4 },
  { left: 51, top: 11, size: 3, seconds: 3.6, delay: -1 },
  { left: 59, top: 28, size: 1, seconds: 5.2, delay: -3 },
  { left: 66, top: 17, size: 2, seconds: 3, delay: -0.4 },
  { left: 74, top: 34, size: 1, seconds: 5.8, delay: -2.8 },
  { left: 82, top: 9, size: 2, seconds: 4.2, delay: -1.9 },
  { left: 90, top: 25, size: 1, seconds: 6.4, delay: -0.9 },
  { left: 95, top: 40, size: 2, seconds: 3.9, delay: -2.4 },
]

export default function SkyBackground({ code, isDay, inset = false }: Props) {
  const { scene, weight } = readingFor(code ?? 802)
  const cover = code === undefined ? 0.4 : cloudCoverFor(scene, weight)

  /*
   * The canvas loop stops while the page is in the background. A phone leaves the
   * page running when the app is switched away, and a few hundred particles a frame
   * is not something to keep doing for a screen nobody is looking at.
   */
  const [visible, setVisible] = useState(true)

  /*
   * The shader draws the sky and the cloud together. If the device cannot give us a
   * WebGL context, or the program will not build, the gradient and the CSS cloud
   * bands below take over and nothing is missing, only softer.
   */
  /*
   * Shared between the two canvases: the rain canvas writes how hard lightning is
   * lighting the sky, the cloud shader reads it. A ref rather than state, because it
   * changes every frame and a render per frame would cost more than the effect.
   */
  const flash = useRef(0)

  const [shaderFailed, setShaderFailed] = useState(false)
  const onShaderFail = useCallback(() => setShaderFailed(true), [])
  const stops = skyStopsFor(scene, weight, isDay)
  useEffect(() => {
    const onChange = () => setVisible(document.visibilityState === 'visible')
    document.addEventListener('visibilitychange', onChange)
    return () => document.removeEventListener('visibilitychange', onChange)
  }, [])

  return (
    <div className={inset ? 'sky sky-inset' : 'sky'} aria-hidden="true">
      {shaderFailed ? (
        <div className="sky-gradient" style={{ background: skyFor(scene, weight, isDay) }} />
      ) : (
        <CloudShader
          skyTop={rgb(stops.top)}
          skyBottom={rgb(stops.bottom)}
          lit={rgb(stops.lit)}
          shadow={rgb(stops.shadow)}
          coverage={cover}
          active={visible}
          flash={flash}
          onFail={onShaderFail}
        />
      )}

      {scene === 'clear' && (
        <>
          {/*
           * Sun or moon, built from the middle out: a wide halo, a bright corona and
           * a hard-edged disc. Sized in vmax and centred on its own point, because a
           * percentage box as wide as the screen gets clipped by the sky's edge and
           * the gradient ends in a straight line down the side.
           */}
          <span
            className="sky-glow"
            style={{
              right: 'calc(18% - 55vmax)', top: 'calc(14% - 55vmax)',
              width: '110vmax', height: '110vmax',
              background: isDay
                ? 'radial-gradient(circle closest-side, rgba(255,236,170,0.30), rgba(255,214,102,0.06) 42%, rgba(255,214,102,0) 70%)'
                : 'radial-gradient(circle closest-side, rgba(203,213,225,0.18), rgba(203,213,225,0) 62%)',
              animationDuration: '13s',
            }}
          />
          <span
            className="sky-glow"
            style={{
              right: 'calc(18% - 19vmax)', top: 'calc(14% - 19vmax)',
              width: '38vmax', height: '38vmax',
              background: isDay
                ? 'radial-gradient(circle closest-side, rgba(255,247,214,0.85), rgba(253,224,71,0.35) 34%, rgba(253,224,71,0) 72%)'
                : 'radial-gradient(circle closest-side, rgba(226,232,240,0.5), rgba(226,232,240,0) 68%)',
              animationDuration: '8s',
            }}
          />
          <span
            className="sky-disc"
            style={{
              right: 'calc(18% - 4.6vmax)', top: 'calc(14% - 4.6vmax)',
              width: '9.2vmax', height: '9.2vmax',
              background: isDay
                ? 'radial-gradient(circle closest-side, #fffdf2 55%, #ffe9a3 88%, rgba(255,233,163,0) 100%)'
                : 'radial-gradient(circle closest-side, #f3f6fb 62%, #cfd9e8 90%, rgba(207,217,232,0) 100%)',
              boxShadow: isDay
                ? '0 0 14vmax 2vmax rgba(255, 226, 140, 0.4)'
                : '0 0 6vmax 1vmax rgba(206, 220, 240, 0.22)',
            }}
          />
          {!isDay && STARS.map((s, i) => (
            <span
              key={i}
              className="sky-star"
              style={{
                left: `${s.left}%`, top: `${s.top}%`,
                width: s.size, height: s.size,
                animationDuration: `${s.seconds}s`, animationDelay: `${s.delay}s`,
              }}
            />
          ))}
        </>
      )}

      {shaderFailed && cover > 0 && BANDS.map((b, i) => (
        <div
          key={i}
          className="sky-cloud-band"
          style={{ top: b.top, height: b.height, opacity: b.opacity * cover }}
        >
          <div
            className="sky-cloud-strip"
            style={{
              backgroundImage: b.tile,
              backgroundSize: b.size,
              animationDuration: `${b.seconds}s`,
              WebkitMaskImage: CLOUD_MASK,
              maskImage: CLOUD_MASK,
              WebkitMaskSize: b.size,
              maskSize: b.size,
            }}
          >
            {/* Light on the crowns and shadow along the base, cut to the same shape. */}
            <div className="sky-cloud-shade" />
          </div>
        </div>
      ))}

      {/* Under a storm the whole sky loses its light, not just the cloud. */}
      {scene === 'storm' && <div className="sky-gloom" />}

      {shaderFailed && cover > 0.45 && (
        <div className="sky-front">
          <div
            className="sky-cloud-strip"
            style={{
              backgroundImage: FRONT_WISP.tile,
              backgroundSize: FRONT_WISP.size,
              animationDuration: `${FRONT_WISP.seconds}s`,
              opacity: FRONT_WISP.opacity * cover,
            }}
          />
        </div>
      )}

      <Precipitation scene={scene} weight={weight} active={visible} flash={flash} />

      {/* Holds text and panels legible over the paler daytime skies. */}
      <div className="sky-scrim" />
    </div>
  )
}
